# Generated by Django 3.2.4 on 2021-07-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_manufacturer_accessory_manufacture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('platforms', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('release', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='console',
            name='game',
            field=models.ManyToManyField(to='main_app.Game'),
        ),
    ]
