# Generated by Django 3.2.4 on 2021-07-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210716_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='console',
            old_name='game',
            new_name='games',
        ),
    ]
