# Generated by Django 3.2.4 on 2021-07-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_game_console_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='Destiny', max_length=100),
            preserve_default=False,
        ),
    ]
